# tmux conf                                                             
set -g default-terminal "screen-256color"                               
set -g terminal-overrides ',xterm-256color:Tc'                          
                                                                          
new-session -n $HOST                                                    
                                                                          
unbind -n C-a                                                           
set -g prefix ^a                                                        
set -g prefix2 F12                                                      
                                                                          
#bind a send-prefix                                                      
#bind P paste-buffer                                                     
                                                                          
set -g mouse on                                                         
set-option -g history-limit 20000

#source "$HOME/.local/lib/python3.6/site-packages/powerline/bindings/tmux/powerline.conf"


